This is a rework of the Python NumPy Tutorial for Beginners (from https://www.youtube.com/watch?v=QUT1VHiLmmI)

# Why is numpy faster?  -Fixed Type
1. Faster to read less bytes of memory.
2. No type checking when iterating through objects.
3. Numpy uses contiguous memory.

# Load in NumPy (remember to pip install numpy first)

In [2]:
import numpy as np

# The Basics

In [27]:
a=np.array([1,2,3],dtype="int64")
print(a)

[1 2 3]


In [20]:
b=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]],dtype="float16")
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
# Get Dimension
print(a.ndim)
print(b.ndim)

1
2


In [10]:
# Get shape
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [21]:
# Get Type
print(a.dtype)
print(b.dtype)

int16
float16


In [28]:
# Get Size
print(a.itemsize)

8
